"""empty message

Revision ID: 162a268c643e
Revises: 
Create Date: 2023-01-03 18:44:45.330222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '162a268c643e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favourite_colour', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('favourite_colour')

    # ### end Alembic commands ###
